#!/usr/bin/python
print "Content-Type: application/json"
print

import gobject
import sys
import dbus
import dbus.mainloop.glib
import re
from optparse import OptionParser, make_option

import MySQLdb
import cgi, cgitb
import json

form = cgi.FieldStorage()
macAddress = form.getvalue('mac')

dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
bus = dbus.SystemBus()
mainloop = gobject.MainLoop()

manager = dbus.Interface(bus.get_object("org.bluez", "/"), "org.bluez.Manager")

option_list = [
		make_option("-i", "--device", action="store",
				type="string", dest="dev_id"),
		]
parser = OptionParser(option_list=option_list)

(options, args) = parser.parse_args()

if options.dev_id:
	adapter_path = manager.FindAdapter(options.dev_id)
else:
	adapter_path = manager.DefaultAdapter()

adapter = dbus.Interface(bus.get_object("org.bluez", adapter_path),
							"org.bluez.Adapter")

# remove from bluetooth device list and unpair

try:
	path = adapter.FindDevice(macAddress)
except:
	print json.dumps({'result':'0', 'mac': macAddress})
	sys.exit(0)

adapter.RemoveDevice(path)

# remove from database

db = MySQLdb.connect(host="localhost", user="root", passwd="1234", db="smart_classroom")
cursor = db.cursor()

sql = "DELETE FROM `btDevice` WHERE `MacAddress` = '" + macAddress + "'"
cursor.execute(sql)	
db.commit()

print json.dumps({'result':'1'})

sys.exit(0)
